---
name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    uses: frontierdigital/shared-workflows/.github/workflows/terraform-workload.yml@v1.0.0-pre.2839fcf
    with:
      workloadName: rancher-server
    secrets:
      armClientId: ${{ secrets.AZURE_CLIENT_ID }}
      armClientSecret: ${{ secrets.AZURE_CLIENT_SECRET }}
      armSubscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      armTenantId: ${{ secrets.AZURE_TENANT_ID }}
